
server:
  port: 8765

spring:
  application:
    name: gateway-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: gateway-server
        url: /v3/api-docs

      - name: identity-service
        url: /identity-service/v3/api-docs

      - name: department-service
        url: /department-service/v3/api-docs

      - name: employee-service
        url: /employee-service/v3/api-docs

      - name: food-service
        url: /food-service/v3/api-docs

      - name: commit-service
        url: /commit-service/v3/api-docs

      - name: media-service
        url: /media-service/v3/api-docs