
server:
  port: 9000

spring:
  application:
    name: department-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        highlight_sql: true
springdoc:
  api-docs:
    path: /department-service/v3/api-docs
  swagger-ui:
    path: /department-service/swagger-ui.html